services:
    AAXIS\Bundle\WebpackBundle\Command\WebpackBuildCommand:
        arguments:
            - '@oro_asset.node_process_factory'
            - '%oro_asset.build_timeout%'
            - '%oro_asset.npm_path%'
            - '%oro_asset.npm_install_timeout%'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command, command: 'aaxis:webpack:build' }
    AAXIS\Bundle\WebpackBundle\Command\DumpWebpackConfigCommand:
        arguments:
            - '@AAXIS\Bundle\WebpackBundle\Provider\WebpackConfigProvider'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command, command: 'aaxis:webpack:dump' }
    AAXIS\Bundle\WebpackBundle\Provider\WebpackConfigProvider:
        arguments:
            - '@oro_layout.theme_manager'
            - '%kernel.bundles%'
            - '%kernel.project_dir%'
    AAXIS\Bundle\WebpackBundle\EventListener\AssetsBuildListener:
        arguments:
            - '@oro_cache.oro_data_cache_manager'
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }